### ISSUE TITLE
Neighbourhood Processing: Initial functionality

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#100]
As an IMPROVER developer,  I want the initial functionality to do neighourbood processing so that I can build upon this in future work to develop smoothly varying fields of probabilistic information.

Acceptance criteria:
 * Complete the subtasks below.

**Subtasks:**

- [x] -  Import neighbourhood processing (#1)
- [x] - Command line interface testing using BATS and application to neighbourhood processing (#5)
- [x] - Add neighbourhood processing CLI acceptance tests and enhance improver tests interface (#72) & associated issue CLI acceptance tests for improver nbhood #59
- [x] - Configurable radius by lead time (#52)

**Comment by fionaRust** [comment]
Closed as all parts are complete
