### ISSUE TITLE
Informal Level 1 archive and retrieval

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#101]
As an IMPROVER developer I want an informal Level 1 archive and utilities to retrieve from it so that I can develop against realistic data and run case studies/trials.

Related tasks: #33, #44, #66.

Subtasks:

- [x]  Write first draft archive retrieval utility  #33
- [x] Choose cases for Level 1 archive #44 
- [x]  Create informal Level 1 archive #66

**Comment by arh89** [comment]
@benfitzpatrick, can this issue now be closed?

**Comment by gavinevans** [comment]
@benfitzpatrick @TomekTrzeciak 
The Level 1 archive now contains standardised MOGREPS-UK output between 1 February 2017 and 30 June 2017 for the 03Z, 09Z, 15Z and 21Z cycles. The output has been grouped into cloud, moisture, precipitation, pressure, temperature, visibility and wind.

Based on the criteria in #44, it appears the desired case studies are covered:
- Unexpected snow - 11 February 2017 - Rain and snow are available.
- Storm Doris - 22-23 February 2017 - Wind, rain and snow are available.
- Low cloud - 5-6 April 2017 - Low cloud available. I don't think there are any diagnostics equivalent to sunshine.
- Wintry showers and wind gusts - 25-25 April 2017 - Rain, snow and gusts are available.
- Sea fog 31 May - 1 June - Visibility at screen level is available.

I think that it would be good to document somewhere, probably on Confluence, the structure of this temporary archive, so that someone can know the structure without having to actually look at the archive. I'm not sure if this information is available anywhere right now. In Nigel's requirements (#44), he notes that there isn't a "clear skies with local fog and cold overnight temperatures" case study at the moment in the archive. Are there plans to find a relevant case study at some point? I note that the document attached to #44 covers some diagnostics, which I don't think are directly within the archive e.g. sunshine. Is this a problem?

**Comment by bayliffe** [comment]
I would suggest that the original Strategy document on confluence become more of a documentation source. We should include the details above (and on ticket #44) that give dates of useful events, and an outline of how to use archive retrieval.

https://exxreldocs:8099/display/TEPPV/Informal+Level+1+Archive+Strategy

**Comment by arh89** [comment]
I have updated the internal page (mentioned above) to contain this information.

**Comment by bayliffe** [comment]
Radiation fog and low temperatures can be obtained from the 4th-6th December 2016. Please look into retrieving this data and I will check with Ben that he is happy to add a non-contiguous component to the archive.

**Comment by bayliffe** [comment]
January 22nd to the beginning of February to be added to the archive by @benfitzpatrick.
@arh89 will then update the documentation, at which point I will close this ticket.

**Comment by bayliffe** [comment]
Data from January 22nd onward now included in archive. The documentation has been updated to reflect this and reference the foggy conditions that were desired.
