### ISSUE TITLE
Generation of probabilistic output - Initial functionality

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#102]
As a users of IMPROVER data I want to have access to probabilistic data so that I can make better use of ensemble data and produce better results

Related issues: **Potential pre-requisite** of knowing how to encode this data in a cf compliant way #91 

Acceptance criteria:
 * Have the the initial capability to produce percentiles and probabilities above thresholds

**Subtasks**

- [x] CLI for threshold plugin, #98 
- [x] Import percentile conversion #69 
- [X] Import threshold plugin

**Comment by fionaRust** [comment]
All subtasks closed so closing ticket.
