### ISSUE TITLE
Wind downscaling: Initial functionality

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#103]
As an IMPROVER developer, I want to integrate wind downscaling into IMPROVER so that I can assess the benefits of wind downscaling.

Acceptance criteria:
 * Completion of the subtasks below

**Subtasks:**
- [x] - Import wind downscaling #14 
Unit tests:
- [ ] - FrictionVelocity.calc_ustar (#19)
- [ ] - RoughnessCorrectionUtilities: refinemask and setmask (#20)
- [ ] - RoughnessCorrectionUtilities.sigma2hover2 (#21)
- [ ] - RoughnessCorrectionUtilities.calc_wav (#22)
- [ ] - RoughnessCorrection.calc_h_ref (#23)
- [ ] - RoughnessCorrection.roughness_correction_sub (#24)
- [ ] - RoughnessCorrectionUtilities.calc_u_at_h (#25)
- [ ] - RoughnessCorrectionUtilties interp1d and loginterpol (#26)
- [ ] - RoughnessCorrection.height_corr_sub (#27)
- [ ] - RoughnessCorrectionUtilities.do_rc_hc_all (#28)
- [ ] - RoughnessCorrection.calc_av_ppgrid_res (#29)
Command line interface:
- [x] - Command line interface for wind downscaling (#67)

**Comment by fionaRust** [comment]
@NigelRoberts, I would like to close this ticket, as the functionality has been added and the outstanding subtasks are all to do with corrections to unit tests which will be covered by technical debt in the Jira backlog.

**Comment by fionaRust** [comment]
Closing as @NigelRoberts  that all outstanding functionality will be covered as technical debt.
