### ISSUE TITLE
Neighbourhood Processing: Fast square neighbourhood and adjust neighbourhood size to ensemble size

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#104]
As a producers of neighbourhood data I want efficient and fully functional code so that we can use neighbourhood processing in a fast and easy to use way.

Related issues: #I, #J

The square neighbourhood approach using #73 and #74 is shown in this flow diagram:

![neighbourhood_4point_flowchart](https://user-images.githubusercontent.com/28624745/27175357-de5877e2-51b6-11e7-8518-3015e9906513.png)

Acceptance criteria:
 * Have a plugin which can use this algorithm.
 * Implement Nigel's algorithm to speed up neighbourhood processing for rectangular neighbourhoods.
 * Ability to adjust neighbourhood size according to ensemble size

**Subtasks**

- [x] Add up array from bottom left to top right - square neighbourhood part 1 #73
   Done: @gavinevans and @meabhnicguidhir
- [x] 4-point square neighbourhood algorithm - square neighbourhood part 2 #74
  Done: @meabhnicguidhir
- [x] Functionality to adjust neighbourhood size according to ensemble size #75
Done: carolinejjones

**Comment by carolinejjones** [comment]
Working on "Functionality to adjust neighbourhood size according to ensemble size" #75

**Comment by gavinevans** [comment]
@benfitzpatrick Items for consideration as technical debt, or documentation improvements.
See https://github.com/metoppv/improver/pull/114#issuecomment-308691613. For unit tests, if the docstring of the unit test has a title string, then that will be included when running the unit tests in verbose mode. See the example below, where `test_basic` has a title string whilst `test_check_coordinate` doesn't have a title string. For example:
```bash
python -m unittest -v test_nbhood_utilities
test_basic (test_nbhood_utilities.Test_find_required_lead_times)
Test that a numpy array is returned. ... ok
test_check_coordinate (test_nbhood_utilities.Test_find_required_lead_times) ... ok
```
Not within this ticket but elsewhere, it might be worth considering whether this has any implications for the style recommendations for the docstrings in unit tests. This work might be somewhat related to #89.

**Comment by gavinevans** [comment]
A slide has been created for the sprint demo.

**Comment by gavinevans** [comment]
Follow-on issues:
@benfitzpatrick has added to the acceptance criteria of #89 to note the advantages of using a title string in the docstrings of the unit tests.

**Comment by MoseleyS** [comment]
#75 is blocked (as PR #129) due to an issue with cube meta-data. See #75 for information.

**Comment by fionaRust** [comment]
Part 3 - the Functionality to adjust neighbourhood size according to ensemble size in #75 has been completed with pull request #129

**Comment by fionaRust** [comment]
Part 2 to do the neighbourhood processing with the new algorithm #74  was completed in pull request #156
