### ISSUE TITLE
Neighbourhood Processing Epic

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#105]
As a product owner I want neighbourhood processing so that we can provide smoother probability fields.

Optional extra information text goes here

Acceptance criteria:
 * Implement basic neighbourhood processing
 * Increase efficiency of code 
 * Add more sophisticated methods

**Stories**

- [x] Initial functionality #100 
- [x] Make Neighbourhood processing more efficient and minor improvement to initial functionality Neighbourhood Processing: Efficiency and minor improvements. #104

Subtasks not yet pulled into a story:
- [ ] Neighbourhood processing: handle variable grid spacings #4
- [ ] Neighbourhood processing: handle domain edge effects #3
- [x] Neighbourhood processing: handle masked arrays #2
- [x] Support for unweighted_mode option

**Comment by fionaRust** [comment]
Closing as all outstanding work is covered by other tickets and we are no longer creating epics on GitHub
