### ISSUE TITLE
Realistic synthetic idealised fields

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#137]
As the product owner I want to be able to test parts of the post processing chain on synthetic but realistic fields.
To start with this should be a north-south valley/ridge in which values are generally lower than elsewhere
The dimensions of the 2-d x-y array need not be large than 50x50.

Related issues: #188, #189 

- [ ] Define, document and create an idealised topography mask with a north-south 3-pixel wide valley/ridge. Can be used to test #188 to apply to a neighbourhood mask.
- [ ] Define, document and create an idealised field with values of 1,2,3,4,5 in which the the values in the north-south valley/ridge can only have values of 1,2 or 3 and the values in the rest of the domain can have values of 3, 4 or 5. Can be used to test #188 to apply to a neighbourhood mask.
- [ ] Define, document and create an idealised precipitation field that varies in time and space over 10 frames. An isolated pixel, with value 2 surrounded by pixels with value 1 in a domain with all other values 0, appears at time T+3 (fourth frame starting from T+0) and persists for 5 frames moving east by one pixel and then disappears at time T+8 to T+10. Can be used to test #189 to apply to time weighting.

Acceptance criteria:
 * Written definition of idealised fields
 * Code available to re-create fields and adapt for variations
 * Visual inspection of idealised fields to check they are correct and image fed into documentation

**Comment by wxtim** [comment]
Looks like the acceptance criteria have been met.

**Comment by gavinevans** [comment]
This has now been completed. 👍
