### ISSUE TITLE
Next tasks for ancillaries epic (introduced July 2017)

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#174]
As the product owner I want IMPROVER to have further orography ancillary functionality. This is part of Epic #97. 

Related issues: #97, #162, #165

There are two tasks with their own issue numbers:
- [x] #162 Generate fields of orography gradient calculated in the x and y directions only (not diagonal).
- [x] #165 Generate a land fraction field that reflects real (as in real world) fractional land area within a given grid square on the UK extended domain.
 
Acceptance criteria:
Task 1
 * Create CLI to enable creation of orography gradient diagnostic using adjacent cell gradient plugin.
 * Produce an example field and check.
Task 2
 *  Obtain data that can be used to generate a fractional land area map across the UK extended domain and ensure this data is formatted suitably for easy reuse in the future (to complete the following step for new standard grids) and put it somewhere accessible.
*   Create a new land_fraction diagnostic by calculating land area within each grid square in the UK extended standard grid V1.

**Comment by bayliffe** [comment]
- [x] slide for orography gradient.
 - [x] slide for land fraction.
