### ISSUE TITLE
Rain or Snow type

### ISSUE THREAD

**Issue by NigelRoberts** [metoppv/improver#191]
As the product owner I want IMPROVER to be able to diagnose the level at which snow will melt. This will be used in conjunction with neighbourhood processing and precipitation type to determine the probability of rain/snow/dry.

This is computed currently in the gridded post processing and the documentation can be found in the PostProcDocType page within the PostProc wiki.

From Stephen Moseley:
This probably divides into tasks to:
•         Calculate 3D wet bulb temperature (from temperature, pressure and relative humidity) – One 10pt story.
In the first instance it would be easier and better to take this from the model using stash code
09222   41 WET BULB TEMPERATURE (K). Then there needs to be a check that this can be computed and output at levels up to ~2000m for the UK. This may require someone to re-run the UKV with the correct stash output. Do we have that expertise - or do we need to look elsewhere in the Met Office for help?
•         Calculate wet bulb integral for each layer from ~2000m to surface. 
•         Determine snow level (ASL) as point where above reaches the specified threshold. – One 10pt story, including previous bullet.
•         Decide whether to keep the specified threshold and whether to retain the nudging determined in the report on the linked page. – This is a bit too open-ended.
•         Fill in gaps where snow level intersects orography by interpolating across the orography.
•         Decide what to do when snow level falls below sea level. Zero isn’t that appropriate as will be under-weighted when merging with another model where the solution is a positive number – fuzzy thresholding would mean that a value of zero could become a Prob(snow to sea level) of 0.5. Perhaps a negative number needs to be determined based on the WBT at sea level. – These last two may also be a 10pt story.

No related issues at present

Work required includes:

- [ ]  Calculation of multi-level wet bulb temperature diagnostic from temperature, pressure, and relative humidity #194
- [ ]   Determine a continuous snow melting level using multi-level wet bulb temperatures #195
- [ ]   Determine suitable threshold values and treatment for snow melting level below sea level #196
- [ ]   Combine snow melting levels from multiple forecasts and create a height-weighted fuzzy melting level
- [ ]  Apply neighbourhood processing along with the fuzzy melting level to obtain snow & rain probabilities appropriate for the altitude of each grid square

There is also a need to determine if wet bulb temperature can be obtained directly from level 1.

Acceptance criteria:
 * Make sure that each of the stages meets its own acceptance criteria

**Comment by bayliffe** [comment]
Suggested form for this ticket:

**Snow melt Epic**

As the product owner I want IMPROVER to be able to diagnose the level at which snow will melt. This will be used in conjunction with neighbourhood processing and precipitation type to determine the probability of rain/snow/dry.

This is computed currently in the gridded post processing and the documentation can be found in the PostProcDocType page within the PostProc wiki.

Work required includes:
* Calculation of multi-level wet bulb temperature diagnostic from temperature, pressure, and relative humidity #194
* Determine a continuous snow falling level using multi-level wet bulb temperatures #195
* Determine suitable threshold values and treatment for snow levels below sea level #196
