### ISSUE TITLE
Migrate functionality from CLI to plugin layer

### ISSUE THREAD

**Issue by cpelley** [metoppv/improver#1998]
Being able to run plugins without going through the CLI layer offers greater flexibility for execution.  It is also a reasonable design principle.  To that end, this issue is to capture efforts to achieve this goal.

## Tasks

- [x] https://github.com/metoppv/improver/issues/2005

Those marked with strikethrough don't require changes as they contain no logic within their CLI layer.
Those marked with  :point_left: represent a subset of CLI which are used by [EPP](https://github.com/MetOffice/epp_workflows/blob/3b31b5fef895850d47c8d9ee55b674be830709b4/lib/python/graph_config/settings/default_settings.py#L19).

- [x] ~improver/cli/aggregate_reliability_tables.py~
- [ ] improver/cli/apply_bias_correction.py - https://github.com/metoppv/improver/pull/2018
  - Basic logic migration.
- [x] ~improver/cli/apply_dz_rescaling.py~
- [ ] improver/cli/apply_emos_coefficients.py
  - New `ApplyEmosCoefficients` meta-plugin.
- [ ] improver/cli/apply_height_adjustment.py
  - https://github.com/metoppv/improver/pull/1996
  - https://github.com/metoppv/improver/pull/2002
- [ ] improver/cli/apply_lapse_rate.py
- [ ] improver/cli/apply_night_mask.py
- [ ] improver/cli/apply_rainforests_calibration.py
- [ ] improver/cli/apply_reliability_calibration.py
- [ ] improver/cli/between_thresholds.py
- [ ] improver/cli/blend_adjacent_points.py
- [ ] improver/cli/blend_cycles_and_realizations.py
- [ ] improver/cli/blend_with_vicinity_and_rename.py
- [ ] improver/cli/calculate_forecast_bias.py
- [ ] improver/cli/categorical_modes.py
- [x] improver/cli/categorical.py :point_left:
  - https://github.com/metoppv/improver/pull/2000
- [ ] improver/cli/clip.py
- [x] improver/cli/cloud_condensation_level.py :point_left:
  - https://github.com/metoppv/improver/pull/2000
- [x] improver/cli/cloud_top_temperature.py :point_left:
  - https://github.com/metoppv/improver/pull/2000
- [ ] improver/cli/collapse_realizations.py
- [x] improver/cli/combine.py :point_left:
  - https://github.com/metoppv/improver/pull/2000(not an empty CubeList)
- [ ] improver/cli/compare.py
- [ ] improver/cli/construct_reliability_tables.py
- [ ] improver/cli/convection_ratio.py
- [x] improver/cli/copy_attributes.py :point_left:
  - https://github.com/metoppv/improver/pull/2000
- [ ] improver/cli/create_grid_with_halo.py
- [ ] improver/cli/enforce_consistent_forecasts.py
- [ ] improver/cli/estimate_dz_rescaling.py
- [ ] improver/cli/estimate_emos_coefficients_from_table.py
- [ ] improver/cli/estimate_emos_coefficients.py
- [ ] improver/cli/expected_value.py
- [ ] improver/cli/extend_radar_mask.py
- [x] improver/cli/extract.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/feels_like_temp.py
- [ ] improver/cli/field_texture.py
- [ ] improver/cli/fill_radar_holes.py
- [x] improver/cli/freezing_rain.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/generate_clearsky_solar_radiation.py
- [ ] improver/cli/generate_landmask_ancillary.py
- [ ] improver/cli/generate_metadata_cube.py
- [ ] improver/cli/generate_orographic_smoothing_coefficients.py
- [ ] improver/cli/generate_percentiles.py
- [ ] improver/cli/generate_realizations.py
- [ ] improver/cli/generate_solar_time.py
- [ ] improver/cli/generate_topography_bands_mask.py
- [ ] improver/cli/generate_topography_bands_weights.py
- [x] improver/cli/hail_fraction.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [x] improver/cli/hail_size.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [x] improver/cli/interpolate_using_difference.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/interpret_metadata.py
- [x] improver/cli/lightning_from_cape_and_precip.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/lightning_multivariate_probability_usaf2024.py
- [ ] improver/cli/manipulate_reliability_table.py
- [x] improver/cli/max_in_height.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/max_in_time_window.py
- [ ] improver/cli/merge.py
- [ ] improver/cli/nbhood_iterate_with_mask.py
- [ ] improver/cli/nbhood_land_and_sea.py
- [x] improver/cli/nbhood.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/neighbour_finding.py
- [ ] improver/cli/normalise_to_reference.py
- [ ] improver/cli/nowcast_accumulate.py
- [ ] improver/cli/nowcast_extrapolate.py
- [ ] improver/cli/nowcast_optical_flow_from_winds.py
- [ ] improver/cli/nowcast_optical_flow.py
- [ ] improver/cli/orographic_enhancement.py
- [x] improver/cli/phase_change_level.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/phase_mask.py
- [x] improver/cli/phase_probability.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/recursive_filter.py
- [ ] improver/cli/regrid.py
- [ ] improver/cli/relabel_to_period.py
- [ ] improver/cli/remake_as_shower_condition.py
- [ ] improver/cli/resolve_wind_components.py
- [ ] improver/cli/shower_condition_probability.py
- [ ] improver/cli/sleet_probability.py
- [ ] improver/cli/snow_fraction.py
- [x] improver/cli/snow_splitter.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/spot_extract.py
  - https://github.com/metoppv/improver/pull/1996
  - https://github.com/metoppv/improver/pull/2002
- [x] improver/cli/standardise.py :point_left:
  - https://github.com/metoppv/improver/pull/2000
- [ ] improver/cli/temp_lapse_rate.py
- [ ] improver/cli/temporal_interpolate.py
- [ ] improver/cli/threshold.py
- [ ] improver/cli/time_lagged_ensembles.py
- [ ] improver/cli/uv_index.py
- [x] improver/cli/vertical_updraught.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/vicinity.py
- [ ] improver/cli/visibility_combine_cloud_base.py
- [ ] improver/cli/weighted_blending.py
- [x] improver/cli/wet_bulb_freezing_level.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [x] improver/cli/wet_bulb_temperature_integral.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [x] improver/cli/wet_bulb_temperature.py :point_left:
- https://github.com/metoppv/improver/pull/2003
- [ ] improver/cli/wind_direction.py
- [ ] improver/cli/wind_downscaling.py
- [ ] improver/cli/wind_gust_diagnostic.py

## Issues

- https://github.com/MetOffice/improver_suite/issues/2079

**Comment by cpelley** [comment]
@bayliffe, just to keep you in the loop.

**Comment by bayliffe** [comment]
Work completed.
