### ISSUE TITLE
Import Site Extraction code

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#34]
As a PWS customer I want some prototype site extraction code in IMPROVER so that I can evaluate site Level 3 data.

Acceptance criteria:
 * Port site-specific extraction code by Ben Ayliffe
 * Unit tests
 * CLI Acceptance tests (Ben F will help)

- [x] Import grid point neighbour finding plugin. #61 
- [x] Import data extraction code. #86 
- [x] Extrema Extraction #152 
- [x] Site input #151 
- [x] Data reading and writing #154 
- [x] Add batch processing framework and CLI. #155

**Comment by bayliffe** [comment]
I am uploading the spotdata routines as they stand. Not complete in any way, but independently functional. Better integration with the rest of improver will come when there are common means for loading diagnostic data, ancillary data etc.

Unit tests exist for the priniple routines of neighbour finding and data extractions. There will be more to follow, but again, there is probably enough code in these two routines to look at for now.

I've included a command line interface for the whole spotdata process in the framework.py. This can be factored out into a standalone CLI.

**Run command:**
python framework.py <config_name>--start_date 20170327 --start_time 0 --length 10

**PYTHONPATH**
If using the pickle file, this needs to point to a component of the existing bestdata suite (see me for details).

**Command line options:**
<config_name> = short_test or pws_default (the latter produces many more diagnostics).
--start_date = date available within diagnostic data at which to start the forecast (unset defaults to today).
--start_time = 24hr clock time at which to start the forecast. (unset defaults to the most recent 6 hour increment),
--length = length in hours of forecast period (unset defaults to 144).

--latitudes = list of latitudes for spotdata sites if not using the pickle file
--longitudes = list of longitudes for spotdata sites if not using the pickle file
--altitudes = list of altitudes for spotdata sites if not using the pickle file (defaults to 0 if unset).
--site_ids = list of site_ids for spotdata sites if not using the pickle file (defaults to order index if unset)


**Needed environment variables:**
export ANCILLARY_PATH=<path to ancillary files, orography, land mask>
export SITE_PATH=<path to site pickle file> if this is in use.
export DIAGNOSTIC_FILE_PATH=<path to diagnostic data root dir> (above chunk designated directories).

**Comment by fionaRust** [comment]
Ooops. Pressed the wrong button. Sorry

**Comment by fionaRust** [comment]
Can we add a list of how this has been split down into separate parts and tick off which ones have been done? And make sure any pull requests are linked on this issue?

**Comment by gavinevans** [comment]
@bayliffe If you could document the follow-on issues that will be required that would be great.

**Comment by bayliffe** [comment]
Done, with a follow up ticket #217 created to cover future work to integrate with suite.
