### ISSUE TITLE
Simple evaluation suite

### ISSUE THREAD

**Issue by benfitzpatrick** [metoppv/improver#68]
As an IMPROVER scientist I want a UK ensemble simple evaluation suite so that I can see how IMPROVER suites will look and slot in my own development for quick testing

Acceptance criteria:
 * Use Gavin's wind demo suite as a rough template
 * Suite should be designed with a nod towards more than one model. (Don't hard code things to a specific model.)
 * Suite should have batching just like a real time suite would
 * Will run on SPICE.
* Add 3 tasks to retrieve data, wind downscaling and members-to-percentiles.

**Prerequisites**
- [x] - Archive retrieval script from #33
- [x] - Wind downscaling CLI from #67  
- [x] - Members-to-percentiles conversion from #69

**Subtasks**
- [x] Write suite

**Comment by bayliffe** [comment]
I'd appreciate it if you could use full names for the relevant groups, e.g. ALGOR could be ALGORITHM, DIAG can be DIAGNOSTICS etc. We don't save ourselves anything by shortening these names and they introduce unnecessary scope for confusion.

**Comment by bayliffe** [comment]
I would also suggest there is plenty of scope for some more explanatory comments to make it easier for people to understand what is going on and where they should fiddle with the suite to achieve their ends.

**Comment by bayliffe** [comment]
Could you please move the setting of paths (e.g. IMPROVER_ANCILLARY_DIR) to the suite .conf file with a variable. I wouldn't expect to modify the suite file to affect such a small change.

**Comment by bayliffe** [comment]
It would be do the above also for the improver_path as not everyone will use the directory structure assumed in this suite.

**Comment by arh89** [comment]
Ah, forgot to move the paths to `suite.rc` - all points have been addressed, please see new version (same location).

**Comment by bayliffe** [comment]
Looks good. Thanks for making those changes.

**Comment by arh89** [comment]
Final version of the suite (following reviews by @benfitzpatrick, @TomekTrzeciak and @bayliffe) has been added to FCM under suite-ID: mi-at447.

**Comment by fionaRust** [comment]
Information about suites is available on confluence in the developer section under Improver Suites

**Comment by fionaRust** [comment]
Slides have been created, Tomek, Ben A and Ben F have looked at it. I've had a quick look.

Demo slides have been written.

Closing ticket
