### ISSUE TITLE
Ensemble Copula Coupling: Provide functionality for verification.

### ISSUE THREAD

**Issue by fionaRust** [metoppv/improver#95]
As a verification scientists I want improved ensemble coupla coupling functionality so that I can have more flexibility as to how I verify output from IMPROVER

Related issues: #I, #J

Optional extra information text goes here

Acceptance criteria:
* Completion of the subtasks below.

**Subtasks**
- [x] - Improve Ensemble Copula Coupling plugins - Issue #30  Pr #49 
- [x] - Create a CLI for Ensemble Copula Coupling - Issue #56 This covered support for percentiles only.
- [x] - Create a CLI for Ensemble Copula Coupling - This is to cover support for probabilities. 
- [ ] - Ensure Ensemble Copula Coupling follows CF conventions #54 #279
- [ ] - Ensure Ensemble Copula Coupling can deal with different types of probability input #55 
- [ ] - Review Ensemble Copula Coupling for spot forecasts #48 
- [x] - Add functionality to suite
- [x] - Removal from StaGE

**Comment by fionaRust** [comment]
No longer using epics this way so this ticket is closed.
