### ISSUE TITLE
Ensemble Calibration: Plugins to suite integration

### ISSUE THREAD

**Issue by gavinevans** [metoppv/improver#96]
As a post-processing suite trialler, I want ensemble calibration functionality to exist and to be able to run this functionality from within a trial suite so that I can verify the improvements obtained from the ensemble calibration

Acceptance criteria:
 * Completion of the subtasks below

The high priority label for June relates to #87 and #51 only as of 13/06/17 (with #15 and #18 already done)

**Subtasks**
- [x] - First version of ensemble calibration suitable for calibrating variables that can be represented using a Gaussian or truncated Gaussian distribution #15, #18 
- [x] - Provide a command line interface for ensemble calibration #87
- [x] - Functionality to load or constrain a training period from existing netCDF files #31 
- [x] - Factor out concatenating cubes functionality from ensemble calibration utilities #51 
- [ ] - Add ensemble calibration functionality to a suite
- [ ] - Removal from StaGE

**Comment by gavinevans** [comment]
@benfitzpatrick Just to note regarding technical infrastructure requirements, there's some functionality described in #31, which would potentially be used within #87, in order to provide greater support for more customisable loading.  For the sake of making progress with #87, the loading functionality is not required immediately, but the work done in #87 would need to refactored later, when #31 has been completed.

**Comment by benfitzpatrick** [comment]
That makes sense, OK

**Comment by fionaRust** [comment]
Closing as no longer using these epics on GitHub
