### ISSUE TITLE
Ancillary Generation for IMPROVER

### ISSUE THREAD

**Issue by meabhnicguidhir** [metoppv/improver#97]
As an IMPROVER developer I want flexible functionality to generate ancillary files so that I can generate any ancillaries needed for new IMPROVER developments easily.

Related issues: 
Initially, several issues were opened for ancillary generation which will be superseded by this epic: #43, #76, #77, #78, #79, #80, #81,  #83, #85.

Functionality will be needed for all ancillaries listed below. For each one, the following acceptance criteria will be applied:
 * Develop plugin(s) to generate the required ancillary.
 * Develop flexible script(s) that can be called from the command line, in order to generate the required ancillary files
 * Develop tests for CLI script(s) and unittests for plugin(s)
 * Check ancillaries (plot, metadata etc)

**NOTE:** StaGE does not currenty produce orography ancillaries or land-sea mask/fraction on all the standard grids. Prerequisites listed are estimated
- [x] Landmask
  Prereqs: landmask/land-fraction field on standard grids.

  The StaGE field should not require much adjustment; a CorrectLandMask plugin has been implemented to ensure there are no non-int/boolean values in the field (see #43).
- [x] Topography bands
  Prereqs: orography on standard grids.
  
  These configurable orography bands will be used in neighbourhood processing routines to filter unsuitable grid points from the neighbourhoods used (ex: to remove grid points in valleys from the neighbourhoods of grid points on hills).
 
  A GenerateOrographyBandAncils plugin has been implemented to generate a mask of land points within a given orography range (see #43). 
- [x] E-W and N-S orography gradient field
  Prereqs: orography on standard grids. 

  These fields will be used when carrying out recursive filtering of probability fields, to avoid spreading probabilities up/down slopes.

  Gradients should be calculated in the x and y directions only (not diagonal). The suggested convention is that the x-direction gradient specified for a grid square relates to the gradient on the eastern edge of that square and the y-direction gradient specified for a grid square relates to the northern edge of that square. Plugin(s) developed should be written to fulfil functionality requirements of this task (orography gradient between adjacent grid squares - originally ticket #76 ) and of ticket #83 (rain rate gradient between adjacent grid squares).

   - [x] Step 1 in rebadged user story #83 to cover creating a general function/utility that can calculate gradients.

- [x] Sea/land grid squares in which there is land/sea
   Prereqs: land-fraction field.

  This relates to "Sub-grid topography ancillaries" in the roadmap. Ancillary field flagging up any points which are specified as land/sea in the Landmask ancillary, but which contain some area of sea/land (ie: mostly-land-some-sea, mostly-sea-some-land grid squares). (Originaly #85)
- [ ] Nearest appropriate point around coasts
  Prereqs: field produced by subtask above (land/sea areas in sea/land grid squares), landmask.
  
  Generate ancillary field pointing to the nearest land/sea grid square for a land/sea site located in a sea/land grid square (originally #85 )
- [ ] Hill/Valley diagnosis field
   Prereqs: orography, orography gradient from the earlier subtask.
  
   Generate an ancillary field categorising land points as hill/valley type. Possibly useful: ValleyIndex ancillary used by the old visibility scheme, topographic index used by the model hydrology scheme. (Originally #77)
- [ ] Distance to nearest coast 
  Prereqs: landmask. (Originally #78)
- [ ] Direction of nearest coast 
   Prereqs: orography gradient ancillary from earlier subtask, landmask, may share functionality with subtask above (to find nearest coast). (Originally #79)
- [ ] Exposure to wind from each direction
  Prereqs: gradient field from earlier subtask?
  
  Generate fields of exposure to winds from each direction of: N, N, E, SE, S, SW, W, NW.  (Originally #80)
- [ ] Masking fields used by GPP fog product 
   Current GPP fog product uses: sea mask (inverse of landmask), ValleyIndex (may be interchangeable with Hill/Valley diagnosis field). (Originally #81).

**Comment by fionaRust** [comment]
No longer using these epic tickets and outstanding requirements are unclear and not needed in the near future so closing
