### ISSUE TITLE
Blending 

### ISSUE THREAD

**Issue by carolinejjones** [metoppv/improver#99]
As a scientist I want the functionality to be able to blend together data so that I can do time-lagging and combine models.

This Epic has multiple parts. Related Issues will be summarised below

Acceptance criteria:
 * Create a weighted blending plugin
 * Different weights can be used against the different inputs. these will be supplied by a separate function.
  * Create a CLI for Blending

**Stories**
- [x] Blending : Initial Weighted Blending Functionality #106  
- [x] Time Lagged Weighted Blending - Issue #107 

**Subtasks which have not be incorporated into a User Story**
- [ ] Add Capability to blend percentiles (Superseded by #175 #166)

**Comment by bayliffe** [comment]
Issues addressed or superseded by other tickets.
